### ISSUE TITLE
Plotly doesn't update after re-compiling

### ISSUE THREAD

**Issue by mdibaiee** [theam/haskell-do#103]
I just tried a simple plotly example, and after changing the code and re-compiling, the output plot does not change, I guess it's related to the JavaScript code being executed somehow, will take a look.

**Comment by NickSeagull** [comment]
Somehow, I cannot reproduce this, what are the steps that are you following?

**Comment by mdibaiee** [comment]
@NickSeagull 
1. Clone this repository: https://github.com/mdibaiee/haskelldo-issue-103
2. Build and run the code
3. Change one of the points in either `sp` or `l`
4. Run again
5. The plot does not change

**Comment by mdibaiee** [comment]
@NickSeagull I re-tried this, it seems to work if I compile a second time, and I'm a little suspicious of the highlighting code, would mind to explain how it works? When is `updateDisplays` triggered and when is the code re-highlighted? :grin:

https://github.com/theam/haskell-do/blob/master/src/common/HaskellDo/Compilation/View.hs#L43

**Comment by NickSeagull** [comment]
Yes, it looks like it is there, I might have introduced a bug 😅 
Basically, it gets a variable from the JS side called `alreadyHighlighted`. This flag is set to `true` after each highlighting, and set to `false` with each compilation.

The problem is in [line 46](https://github.com/theam/haskell-do/blob/master/src/common/HaskellDo/Compilation/View.hs#L46) we render the `outputDisplay`, if not, we don't do it, that's why it doesn't render by clicking compile in the toolbar either.

This is the main reason why the render doesn't get updated the first time 🤔

**Comment by mdibaiee** [comment]
@NickSeagull I see, seems like it means "already compiled" rather than "already highlighted" really, and I guess we do need that state, but why in the JavaScript? Can't we achieve the same thing by having a key in our state? :grin:

**Comment by NickSeagull** [comment]
Umm, probably, it's just that it was _really-ultra-quick-rapid-hotfix_ that I did because a lot of people were complaining 😅

**Comment by mdibaiee** [comment]
@NickSeagull :joy: I will see what I can do :grin:

**Comment by NickSeagull** [comment]
Great, thanks! :D

**Comment by mdibaiee** [comment]
@NickSeagull addressed in #106
