### ISSUE TITLE
Open existing projects

### ISSUE THREAD

**Issue by NickSeagull** [theam/haskell-do#2]

**Comment by kitfre** [comment]
I've begun work on this today! When I've finished you'll be able to edit any haskell file on your system, with or without a stack project. And no more overwriting `Main.hs` 😛 

Edit: As an update, I've got it working so that whatever file you edit will not be overwritten and your work persists! Next up I'm going to begin work on allowing a user to edit any file they wish!

**Comment by kitfre** [comment]
Closed now with merge of #24?

**Comment by NickSeagull** [comment]
@KitFreddura indeed 😉
