### ISSUE TITLE
Add MathJax support for rendering inline math

### ISSUE THREAD

**Issue by ocramz** [theam/haskell-do#25]
https://www.mathjax.org/

**Comment by mdibaiee** [comment]
[KaTeX](https://khan.github.io/KaTeX/) is much [faster](http://www.intmath.com/cg5/katex-mathjax-comparison.php) and more efficient. It also supports server-side rendering.

**Comment by NickSeagull** [comment]
@mdibaiee I'm going to try to implement this today, as I'm using lots of equations right now and making screenshots of the equations and uploading them is a bit uncomfortable.

Also, I'm going to use **MathJax** because, even if it is slower, it allows using some non-standard LaTeX packages like [ `amscd` ](http://mirror.isoc.org.il/pub/ctan/macros/latex/required/amslatex/math/amscd.pdf), which allows one to make commutative diagrams like 
![image](https://user-images.githubusercontent.com/7448243/29673357-e7028420-88e6-11e7-9c0b-afcaca245c48.png)
which is really useful for Haskell.

KaTeX doesnt support this sadly.

I think it is worth to have this *non-efficient* way of rendering equations.

**Comment by NickSeagull** [comment]
There we go 
![image](https://user-images.githubusercontent.com/7448243/29675647-af3c053c-88ed-11e7-8ba7-4203de480994.png)
