### ISSUE TITLE
Implement a button to hide text editor in web interface

### ISSUE THREAD

**Issue by ddrone** [theam/haskell-do#86]
Subject.

Can be useful for looking at the finished document potentially supporting a workflow with using external editor instead of builtin one.

**Comment by NickSeagull** [comment]
Absolutely, it would be a matter of adding another `Widget` to the `Toolbar.View` module. Take into account that you have to make a "placeholder" div in the `view` function.

Right now it has to be done this way, because events are handling somewhat manually. If we manage to solve #84 in the future, the development would be a bliss. 😄

**Comment by NickSeagull** [comment]
Closing! Thanks :)
